backend:
  name: git-gateway
  branch: main

media_folder: "images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "news"
    label: "Breaking News"
    folder: "news"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "Layout", name: "layout", widget: "hidden", default: "blog" }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Featured Image", name: "thumbnail", widget: "image" }
      - { label: "Short Description", name: "description", widget: "text" }
      - { label: "Full News Content", name: "body", widget: "markdown" }
      - { label: "Category", name: "category", widget: "select", options: ["National", "Sports", "Local", "Tech"] }

